In [1]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [5]:
df=pd.read_csv("C:\\Users\\LENOVO\\OneDrive\\Desktop\\Machine learning project\\gurgaon_properties.xls")

In [7]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
351,2 BHK Flat in Sector 107 Gurgaon,flat,signature global solera,0.28,5623.0,498.0,Carpet area: 489 (45.43 sq.m.),2,2,2,not available,"Sector 107 Gurgaon, Gurgaon, Haryana",14.0,North-West,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...",This 2 bhk apartment is available for sale in ...,"['1 Wardrobe', '3 Fan', '1 Exhaust Fan', '3 Li...","['Power Back-up', 'Security / Fire Alarm', 'In...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
2150,4 Bedroom House for sale in DLF Phase 2,house,dlf city plots phase 2,6.30,35000.0,(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),4,4,3+,pooja room,"Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...",This is a four bedroom house in dlf phase - 2 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
845,6 Bedroom House for sale in Sector 47 Gurgaon,house,independent,4.30,29311.0,(136 sq.m.) Plot Area,Plot area 163(136.29 sq.m.),6,4,2,servant room,"Sector 47 Gurgaon, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...","Ground, first , second floor with basement.Low...",[],NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2374,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12782.0,1150.0,Carpet area: 1150 (106.84 sq.m.),2,2,2,study room,"J48d, Sector 61 Gurgaon, Gurgaon, Haryana",4.0,East,Sep 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Very beautiful 4th floor with terrace,"['2 Geyser', '2 AC', '1 Modular Kitchen', 'No ...","['Lift(s)', 'Swimming Pool', 'Natural Light', ...",NaN
1643,3 BHK Flat in Gwal Pahari,flat,suncity vatsal valley,1.28,9552.0,1340.0,Carpet area: 1340 (124.49 sq.m.),3,3,3,not available,"Gwal Pahari, Gurgaon, Haryana",1.0,North,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Banjara Market...",Suncity vatsal valley is one of gurgaon's most...,"['3 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN

In [9]:
df.shape

(3961, 20)

In [11]:
df.duplicated().sum()

0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3960 non-null   object
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3960 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 619.0+ KB

In [15]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                  1
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        1
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [17]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 79 Gurgaon,flat,mapsko mount ville,1.30,8024.0,1620.0,Super Built up area 1620(150.5 sq.m.)Carpet ar...,3,3,2,"study room,pooja room","Sector 79 Gurgaon, Gurgaon, Haryana",6.0,West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This beautiful 3 bhk flat in sector 79 gurgaon...,"['6 Wardrobe', '1 Stove', '1 Chimney', '4 AC',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,4 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,5.20,10726.0,4848.0,Super Built up area 4848(450.39 sq.m.)Built Up...,4,6,3+,"servant room,pooja room","301, Sector 112 Gurgaon, Gurgaon, Haryana",15.0,East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",This 4 bhk apartment is available for sale in ...,"['6 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sohna,flat,signature global park,0.95,7846.0,1211.0,Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...,3,2,3+,not available,"Sohna, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Low rise building, all amenities are available...",[],"['Security / Fire Alarm', 'Lift(s)', 'Swimming...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
3,4 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,3.99,8866.0,(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),4,5,3+,servant room,"Nirvana Country, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",This is an newly constructed villa located in ...,"['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,1.40,8861.0,1580.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,"On Spr Road, Sector 69 Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Tulip violet is one of the most popular destin...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."

In [19]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [23]:
df['property_name'].str.split('in')

0                       [3 BHK Flat ,  Sector 79 Gurgaon]
1                      [4 BHK Flat ,  Sector 112 Gurgaon]
2                                   [3 BHK Flat ,  Sohna]
3           [4 Bedroom House for sale ,  Nirvana Country]
4                       [3 BHK Flat ,  Sector 69 Gurgaon]
5                       [3 BHK Flat ,  Sector 31 Gurgaon]
6                         [3 BHK Flat ,  Sector-33 Sohna]
7                      [3 BHK Flat ,  Sector 109 Gurgaon]
8                         [3 BHK Flat ,  Sector-33 Sohna]
9          [5 Bedroom House for sale ,  Sector 7 Gurgaon]
10       [4 Bedroom House for sale ,  Sector 109 Gurgaon]
11                      [3 BHK Flat ,  Sector 90 Gurgaon]
12               [5 Bedroom House for sale ,  New Colony]
13                      [3 BHK Flat ,  Sector 83 Gurgaon]
14                      [3 BHK Flat ,  Sector 81 Gurgaon]
15                      [3 BHK Flat ,  Sector 70 Gurgaon]
16                      [3 BHK Flat ,  Sector 68 Gurgaon]
17                      [2 BHK Flat ,  Sector 84 Gurgaon]
18                     [2 BHK Flat ,  Sector 70A Gurgaon]
19                     [5 BHK Flat ,  Sector 82A Gurgaon]
20                     [2 BHK Flat ,  Sector 104 Gurgaon]
21                      [3 BHK Flat ,  Sector 95 Gurgaon]
22                      [2 BHK Flat ,  Sector 79 Gurgaon]
23                      [3 BHK Flat ,  Sector 65 Gurgaon]
24         [5 Bedroom House for sale ,  Sector 5 Gurgaon]
25                [5 Bedroom House for sale ,  Madanpuri]
26                      [3 BHK Flat ,  Sector 89 Gurgaon]
27                        [3 BHK Flat ,  Nirvana Country]
28                      [2 BHK Flat ,  Sector 86 Gurgaon]
29                      [3 BHK Flat ,  Sector 49 Gurgaon]
30                        [3 BHK Flat ,  Sector-33 Sohna]
31                     [2 BHK Flat ,  Sector 107 Gurgaon]
32      [2 Bedroom House for sale ,  Palam Vihar Exten...
33                     [3 BHK Flat ,  Sector 102 Gurgaon]
34                     [3 BHK Flat ,  Sector 102 Gurgaon]
35             [2 Bedroom House for sale ,  Baldev Nagar]
36                      [3 BHK Flat ,  Sector 69 Gurgaon]
37                      [3 BHK Flat ,  Sector 56 Gurgaon]
38                                  [2 BHK Flat ,  Sohna]
39                      [3 BHK Flat ,  Sector 48 Gurgaon]
40                                  [2 BHK Flat ,  Sohna]
41                     [3 BHK Flat ,  Sector 103 Gurgaon]
42                      [3 BHK Flat ,  Sector 60 Gurgaon]
43                     [3 BHK Flat ,  Sector 113 Gurgaon]
44                        [3 BHK Flat ,  Sector-33 Sohna]
45                      [2 BHK Flat ,  Sector 70 Gurgaon]
46         [3 Bedroom House for sale ,  Sector 3 Gurgaon]
47                      [3 BHK Flat ,  Sector 81 Gurgaon]
48              [5 Bedroom House for sale ,  DLF Phase 2]
49        [1 Bedroom House for sale ,  Sector 39 Gurgaon]
50                     [2 BHK Flat ,  Sector 37C Gurgaon]
51                                  [1 BHK Flat ,  Sohna]
52                      [3 BHK Flat ,  Sector 92 Gurgaon]
53                      [3 BHK Flat ,  Sector 78 Gurgaon]
54                     [2 BHK Flat ,  Sector 108 Gurgaon]
55                      [2 BHK Flat ,  Sector 85 Gurgaon]
56                      [4 BHK Flat ,  Sector 90 Gurgaon]
57                      [3 BHK Flat ,  Sector 89 Gurgaon]
58                      [1 BHK Flat ,  Sector 95 Gurgaon]
59                      [3 BHK Flat ,  Sector 79 Gurgaon]
60            [5 Bedroom House for sale ,  Subhash Nagar]
61                      [2 BHK Flat ,  Sector 61 Gurgaon]
62      [4 Bedroom House for sale ,  Hsiidc Plot Secto...
63             [6 Bedroom House for sale ,  Laxman Vihar]
64      [1 Bedroom House for sale ,  devi lal colony g...
65                      [3 BHK Flat ,  Sector 79 Gurgaon]
66                      [3 BHK Flat ,  Sector 90 Gurgaon]
67                      [3 BHK Flat ,  Sector 81 Gurgaon]
68                     [2 BHK Flat ,  Sector 67A Gurgaon]
69                      [4 BHK Flat ,  Sector 90 Gurgaon]
70                      [2 BHK Flat ,  Sector 90 Gurgaon]
71             [2 Bedroom House for sale ,  Laxman Vihar]
72                      [4 BHK Flat ,  Sector 91 Gurgaon]
73              [6 Bedroom House for sale ,  DLF Phase 2]
74                      [3 BHK Flat ,  Sector 53 Gurgaon]
75        [5 Bedroom House for sale ,  Sector 33 Gurgaon]
76      [5 Bedroom House for sale ,  Sushant Lok Phase 1]
77                      [1 BHK Flat ,  Sector 95 Gurgaon]
78            [4 Bedroom House for sale ,  Rajendra Park]
79                                [3 BHK Flat ,  Suncity]
80             [2 Bedroom House for sale ,  Pratap Nagar]
81                     [3 BHK Flat ,  Sector 112 Gurgaon]
82                      [3 BHK Flat ,  Sector 90 Gurgaon]
83                     [2 BHK Flat ,  Carterpuri Village]
84             [16 Bedroom House for sale ,  DLF Phase 1]
85                        [3 BHK Flat ,  Sector-33 Sohna]
86              [3 Bedroom House for sale ,  Arjun Nagar]
87                      [4 BHK Flat ,  Sector 41 Gurgaon]
88                      [4 BHK Flat ,  Sector 54 Gurgaon]
89                      [3 BHK Flat ,  Sector 92 Gurgaon]
90                     [3 BHK Flat ,  Sector 37D Gurgaon]
91                      [3 BHK Flat ,  Sector 65 Gurgaon]
92                     [3 BHK Flat ,  Sector 104 Gurgaon]
93                       [1 BHK Flat ,  Sector 2 Gurgaon]
94                        [2 BHK Flat ,  Sector-33 Sohna]
95                     [3 BHK Flat ,  Sector 37C Gurgaon]
96             [10 Bedroom House for sale ,  Rajiv Nagar]
97                      [4 BHK Flat ,  Sector 66 Gurgaon]
98                      [3 BHK Flat ,  Sector 67 Gurgaon]
99                     [3 BHK Flat ,  Sector 113 Gurgaon]
100                  [4 BHK Flat ,  Sector 110 A Gurgaon]
101                     [2 BHK Flat ,  Sector 65 Gurgaon]
102                 [3 BHK Flat ,  Sector 1A IMT Manesar]
103                     [2 BHK Flat ,  Sector 61 Gurgaon]
104                     [3 BHK Flat ,  Sector 49 Gurgaon]
105                     [3 BHK Flat ,  Sector 70 Gurgaon]
106                     [2 BHK Flat ,  Sector 67 Gurgaon]
107                     [4 BHK Flat ,  Sector 9A Gurgaon]
108                     [2 BHK Flat ,  Sector 89 Gurgaon]
109                     [3 BHK Flat ,  Sector 65 Gurgaon]
110                       [2 BHK Flat ,  New Palam Vihar]
111                    [3 BHK Flat ,  Sector 102 Gurgaon]
112                  [3 BHK Flat ,  Sector 1 Imt Manesar]
113                     [3 BHK Flat ,  Sector 79 Gurgaon]
114                    [3 BHK Flat ,  Sector 37C Gurgaon]
115                    [3 BHK Flat ,  Sector 102 Gurgaon]
116     [9 Bedroom House for sale ,  C Block Sushant L...
117     [4 Bedroom House for sale ,  Ashok Vihar Phase...
118                     [3 BHK Flat ,  Sector 83 Gurgaon]
119             [5 Bedroom House for sale ,  DLF Phase 2]
120                     [2 BHK Flat ,  Sector 81 Gurgaon]
121       [3 Bedroom House for sale ,  Sector 38 Gurgaon]
122                     [3 BHK Flat ,  Sector 56 Gurgaon]
123                     [3 BHK Flat ,  Sector 83 Gurgaon]
124                     [4 BHK Flat ,  Sector 71 Gurgaon]
125                           [2 BHK Flat ,  Ashok Vihar]
126                    [2 BHK Flat ,  Sector 107 Gurgaon]
127                    [3 BHK Flat ,  Sector 37D Gurgaon]
128                    [3 BHK Flat ,  Sector 107 Gurgaon]
129                      [3 BHK Flat ,  Sector 1 Gurgaon]
130                    [3 BHK Flat ,  Sector 106 Gurgaon]
131                     [2 BHK Flat ,  Sector 65 Gurgaon]
132                     [2 BHK Flat ,  Sector 85 Gurgaon]
133                    [3 BHK Flat ,  Sector 107 Gurgaon]
134     [5 Bedroom House for sale ,  Sushant Lok Phase 1]
135                    [2 BHK Flat ,  Sector 37D Gurgaon]
136                                 [2 BHK Flat ,  Sohna]
137       [4 Bedroom House for sale ,  Sector 42 Gurgaon]
138                     [4 BHK Flat ,  Sector 56 Gurgaon]
139                     [4 BHK Flat ,  Sector 59 Gurgaon]
140                    [3 BHK Flat ,  Sector 103 Gurgaon]
141       [3 Bedroom House for sale ,  Sector 14 Gurgaon]
142                     [4 BHK Flat ,  Sector 70 Gurgaon]
143                 [4 Bedroom House for sale ,  Suncity]
144       [5 Bedroom House for sale ,  Sector 33 Gurgaon]
145                     [3 BHK Flat ,  Sector 65 Gurgaon]
146                                 [2 BHK Flat ,  Sohna]
147                     [2 BHK Flat ,  Sector 85 Gurgaon]
148                                 [3 BHK Flat ,  Sohna]
149      [1 Bedroom House for sale ,  Sector 108 Gurgaon]
150                      [2 BHK Flat ,  Golf Course Road]
151      [3 Bedroom House for sale ,  Sector 63A Gurgaon]
152             [4 Bedroom House for sale ,  Malibu Town]
153                     [2 BHK Flat ,  Sector 69 Gurgaon]
154                    [3 BHK Flat ,  Sector 37C Gurgaon]
155      [5 Bedroom House for sale ,  Sector 109 Gurgaon]
156                    [2 BHK Flat ,  Sector 37C Gurgaon]
157                     [4 BHK Flat ,  Sector 72 Gurgaon]
158                     [3 BHK Flat ,  Sector 90 Gurgaon]
159                     [2 BHK Flat ,  Sector 95 Gurgaon]
160              [3 Bedroom House for sale ,  Sohna Road]
161                           [5 BHK Flat ,  Gwal Pahari]
162                     [3 BHK Flat ,  Sector 89 Gurgaon]
163                    [2 BHK Flat ,  Sector 70A Gurgaon]
164                     [4 BHK Flat ,  Sector 92 Gurgaon]
165                    [2 BHK Flat ,  Sector 37C Gurgaon]
166                     [2 BHK Flat ,  Sector 68 Gurgaon]
167             [4 Bedroom House for sale ,  Palam Vihar]
168                    [3 BHK Flat ,  Sector 109 Gurgaon]
169                    [4 BHK Flat ,  Sector 112 Gurgaon]
170                     [4 BHK Flat ,  Sector 85 Gurgaon]
171                     [4 BHK Flat ,  Sector 90 Gurgaon]
172                     [1 BHK Flat ,  Sector 95 Gurgaon]
173       [4 Bedroom House for sale ,  Sector 66 Gurgaon]
174                     [3 BHK Flat ,  Sector 82 Gurgaon]
175                     [3 BHK Flat ,  Sector 65 Gurgaon]
176                                 [2 BHK Flat ,  Sohna]
177                    [2 BHK Flat ,  Sector 102 Gurgaon]
178                     [3 BHK Flat ,  Sector 95 Gurgaon]
179                     [3 BHK Flat ,  Sector 70 Gurgaon]
180                    [3 BHK Flat ,  Sector 109 Gurgaon]
181                     [3 BHK Flat ,  Sector 81 Gurgaon]
182                     [2 BHK Flat ,  Sector 85 Gurgaon]
183               [8 Bedroom House for sale ,  New Basti]
184                     [3 BHK Flat ,  Sector 83 Gurgaon]
185                                 [3 BHK Flat ,  Sohna]
186                       [4 BHK Flat ,  Sector-33 Sohna]
187                    [3 BHK Flat ,  Sector 108 Gurgaon]
188                     [2 BHK Flat ,  Sector 51 Gurgaon]
189                    [4 BHK Flat ,  Sector 110 Gurgaon]
190                           [3 BHK Flat ,  IMT Manesar]
191                     [2 BHK Flat ,  Sector 68 Gurgaon]
192                     [4 BHK Flat ,  Sector 62 Gurgaon]
193       [4 Bedroom House for sale ,  Sector 82 Gurgaon]
194                     [2 BHK Flat ,  Sector 86 Gurgaon]
195                     [4 BHK Flat ,  Sector 53 Gurgaon]
196                     [4 BHK Flat ,  Sector 92 Gurgaon]
197         [5 Bedroom House for sale ,  Mianwali Colony]
198                     [3 BHK Flat ,  Sector 69 Gurgaon]
199                     [1 BHK Flat ,  Sector 95 Gurgaon]
200                     [3 BHK Flat ,  Sector 51 Gurgaon]
201                     [4 BHK Flat ,  Sector 92 Gurgaon]
202       [9 Bedroom House for sale ,  Sector 47 Gurgaon]
203                  [3 BHK Flat ,  Sector 1 Imt Manesar]
204                     [3 BHK Flat ,  Sector 79 Gurgaon]
205                     [2 BHK Flat ,  Sector 81 Gurgaon]
206                    [3 BHK Flat ,  Sector 109 Gurgaon]
207        [2 Bedroom House for sale ,  Sector 6 Gurgaon]
208                    [2 BHK Flat ,  Sector 103 Gurgaon]
209             [9 Bedroom House for sale ,  DLF Phase 2]
210                    [2 BHK Flat ,  Sector 37D Gurgaon]
211                    [4 BHK Flat ,  Sector 111 Gurgaon]
212       [2 Bedroom House for sale ,  Sector 31 Gurgaon]
213             [5 Bedroom House for sale ,  Rajiv Nagar]
214                     [3 BHK Flat ,  Sector 70 Gurgaon]
215           [7 Bedroom House for sale ,  Rajendra Park]
216                     [4 BHK Flat ,  Sector 72 Gurgaon]
217                     [3 BHK Flat ,  Sector 30 Gurgaon]
218                     [3 BHK Flat ,  Sector 69 Gurgaon]
219                          [2 BHK Flat ,  Laxman Vihar]
220                    [2 BHK Flat ,  Sector 102 Gurgaon]
221                    [4 BHK Flat ,  Sector 102 Gurgaon]
222                     [3 BHK Flat ,  Sector 61 Gurgaon]
223                     [3 BHK Flat ,  Sector 65 Gurgaon]
224                    [4 BHK Flat ,  Sector 82A Gurgaon]
225                     [3 BHK Flat ,  Sector 92 Gurgaon]
226                                 [2 BHK Flat ,  Sohna]
227                       [3 BHK Flat ,  Nirvana Country]
228      [5 Bedroom House for sale ,  Sector 108 Gurgaon]
229     [4 Bedroom House for sale ,  G block DLF City ...
230                     [3 BHK Flat ,  Sector 49 Gurgaon]
231                     [2 BHK Flat ,  Sector 85 Gurgaon]
232                     [4 BHK Flat ,  Sector 90 Gurgaon]
233                     [3 BHK Flat ,  Sector 92 Gurgaon]
234                                 [3 BHK Flat ,  Sohna]
235                     [3 BHK Flat ,  Sector 92 Gurgaon]
236                     [3 BHK Flat ,  Sector 65 Gurgaon]
237                    [2 BHK Flat ,  Sector 102 Gurgaon]
238          [4 Bedroom House for sale ,  Tekchand Nagar]
239                           [2 BHK Flat ,  Patel Nagar]
240                    [2 BHK Flat ,  Sector 88A Gurgaon]
241                               [3 BHK Flat ,  Bhondsi]
242                    [3 BHK Flat ,  Sector 82A Gurgaon]
243                     [3 BHK Flat ,  Sector 84 Gurgaon]
244                     [2 BHK Flat ,  Sector 81 Gurgaon]
245                     [4 BHK Flat ,  Sector 69 Gurgaon]
246                     [4 BHK Flat ,  Sector 51 Gurgaon]
247                     [3 BHK Flat ,  Sector 70 Gurgaon]
248                    [2 BHK Flat ,  Sector 37C Gurgaon]
249     [1 Bedroom House for sale ,  Laxman Vihar, Rai...
250                     [1 BHK Flat ,  Sector 28 Gurgaon]
251                                 [1 BHK Flat ,  Sohna]
252                    [3 BHK Flat ,  Sector 104 Gurgaon]
253       [4 Bedroom House for sale ,  Sector 67 Gurgaon]
254                                 [2 BHK Flat ,  Sohna]
255                     [3 BHK Flat ,  Sector 65 Gurgaon]
256       [5 Bedroom House for sale ,  Sector 14 Gurgaon]
257      [4 Bedroom House for sale ,  Sector 103 Gurgaon]
258       [3 Bedroom House for sale ,  Sector 14 Gurgaon]
259                    [3 BHK Flat ,  Sector 37C Gurgaon]
260                     [2 BHK Flat ,  Sector 85 Gurgaon]
261                    [3 BHK Flat ,  Sector 109 Gurgaon]
262                     [3 BHK Flat ,  Sector 54 Gurgaon]
263                     [4 BHK Flat ,  Sector 90 Gurgaon]
264                     [2 BHK Flat ,  sector 58 Gurgaon]
265                                 [3 BHK Flat ,  Sohna]
266                    [2 BHK Flat ,  Sector 107 Gurgaon]
267                     [2 BHK Flat ,  Sector 95 Gurgaon]
268                     [4 BHK Flat ,  Sector 85 Gurgaon]
269                                 [3 BHK Flat ,  Sohna]
270                     [3 BHK Flat ,  Sector 77 Gurgaon]
271                    [2 BHK Flat ,  Sector 108 Gurgaon]
272                                 [2 BHK Flat ,  Sohna]
273                           [3 BHK Flat ,  IFFCO Chowk]
274       [5 Bedroom House for sale ,  Sector 72 Gurgaon]
275                     [4 BHK Flat ,  Sector 69 Gurgaon]
276                    [2 BHK Flat ,  Sector 88A Gurgaon]
277         [4 Bedroom House for sale ,  Nirvana Country]
278                     [3 BHK Flat ,  Sector 85 Gurgaon]
279                    [1 BHK Flat ,  Sector 107 Gurgaon]
280                            [3 BHK Flat ,  Chakkarpur]
281                     [1 BHK Flat ,  Sector 52 Gurgaon]
282                 [4 BHK Flat ,  Mehrauli Gurgaon Road]
283                    [3 BHK Flat ,  Sector 37D Gurgaon]
284                     [2 BHK Flat ,  Sector 79 Gurgaon]
285                     [1 BHK Flat ,  Sector 51 Gurgaon]
286         [7 Bedroom House for sale ,  Mianwali Colony]
287                  [4 BHK Flat ,  Sector 1 Imt Manesar]
288       [4 Bedroom House for sale ,  Sector 54 Gurgaon]
289                     [2 BHK Flat ,  Sector 79 Gurgaon]
290     [2 Bedroom House for sale ,  Ashok Vihar Phase 3]
291                           [3 BHK Flat ,  Palam Vihar]
292                     [3 BHK Flat ,  Sector 70 Gurgaon]
293     [6 Bedroom House for sale ,  Sushant Lok Phase 1]
294                    [3 BHK Flat ,  Sector 107 Gurgaon]
295                       [2 BHK Flat ,  Sector-33 Sohna]
296                     [3 BHK Flat ,  Sector 79 Gurgaon]
297                    [3 BHK Flat ,  Sector 113 Gurgaon]
298            [6 Bedroom House for sale ,  Laxmi Garden]
299               [4 Bedroom House for sale ,  Jacobpura]
300       [6 Bedroom House for sale ,  Sector 33 Gurgaon]
301                     [4 BHK Flat ,  Sector 85 Gurgaon]
302                     [3 BHK Flat ,  Sector 84 Gurgaon]
303                     [2 BHK Flat ,  Sector 95 Gurgaon]
304                           [3 BHK Flat ,  Palam Vihar]
305                    [4 BHK Flat ,  Sector 113 Gurgaon]
306                     [2 BHK Flat ,  Sector 81 Gurgaon]
307        [3 Bedroom House for sale ,  Sector 9 Gurgaon]
308        [5 Bedroom House for sale ,  Sector 3 Gurgaon]
309                     [3 BHK Flat ,  Sector 92 Gurgaon]
310                     [2 BHK Flat ,  Sector 95 Gurgaon]
311                        [2 BHK Flat ,  Krishna Colony]
312                     [3 BHK Flat ,  Sector 61 Gurgaon]
313      [3 Bedroom House for sale ,  Sector 70A Gurgaon]
314     [7 Bedroom House for sale ,  Sushant Lok Phase 1]
315                    [3 BHK Flat ,  Sector 103 Gurgaon]
316       [4 Bedroom House for sale ,  Sector 28 Gurgaon]
317                     [2 BHK Flat ,  Sector 81 Gurgaon]
318                     [2 BHK Flat ,  Sector 83 Gurgaon]
319                    [4 BHK Flat ,  Sector 107 Gurgaon]
320                     [3 BHK Flat ,  Sector 59 Gurgaon]
321                                 [2 BHK Flat ,  Sohna]
322       [4 Bedroom House for sale ,  Sector 66 Gurgaon]
323                     [3 BHK Flat ,  Sector 80 Gurgaon]
324                     [3 BHK Flat ,  Sector 47 Gurgaon]
325                    [3 BHK Flat ,  Sector 82A Gurgaon]
326                     [2 BHK Flat ,  Sector 85 Gurgaon]
327                    [3 BHK Flat ,  Sector 104 Gurgaon]
328                    [2 BHK Flat ,  Sector 107 Gurgaon]
329                     [3 BHK Flat ,  Sector 89 Gurgaon]
330                     [3 BHK Flat ,  Sector 83 Gurgaon]
331                     [3 BHK Flat ,  Sector 85 Gurgaon]
332                     [2 BHK Flat ,  Sector 84 Gurgaon]
333                     [3 BHK Flat ,  Sector 95 Gurgaon]
334                     [3 BHK Flat ,  Sector 66 Gurgaon]
335                     [2 BHK Flat ,  Sector 90 Gurgaon]
336                 [2 BHK Flat ,  Sector 4 Urban Estate]
337             [4 Bedroom House for sale ,  Palam Vihar]
338                     [2 BHK Flat ,  Sector 93 Gurgaon]
339                    [3 BHK Flat ,  Sector 37C Gurgaon]
340                     [2 BHK Flat ,  Sector 78 Gurgaon]
341                     [4 BHK Flat ,  Sector 85 Gurgaon]
342                    [2 BHK Flat ,  Sector 70A Gurgaon]
343            [10 Bedroom House for sale ,  DLF Phase 3]

In [27]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 79 Gurgaon,flat,mapsko mount ville,Sector 79,1.30,8024.0,1620.0,Super Built up area 1620(150.5 sq.m.)Carpet ar...,3,3,2,"study room,pooja room","Sector 79 Gurgaon, Gurgaon, Haryana",6.0,West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This beautiful 3 bhk flat in sector 79 gurgaon...,"['6 Wardrobe', '1 Stove', '1 Chimney', '4 AC',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,4 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,Sector 112,5.20,10726.0,4848.0,Super Built up area 4848(450.39 sq.m.)Built Up...,4,6,3+,"servant room,pooja room","301, Sector 112 Gurgaon, Gurgaon, Haryana",15.0,East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",This 4 bhk apartment is available for sale in ...,"['6 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sohna,flat,signature global park,Sohna,0.95,7846.0,1211.0,Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...,3,2,3+,not available,"Sohna, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Low rise building, all amenities are available...",[],"['Security / Fire Alarm', 'Lift(s)', 'Swimming...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
3,4 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,Nirvana Country,3.99,8866.0,(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),4,5,3+,servant room,"Nirvana Country, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",This is an newly constructed villa located in ...,"['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,Sector 69,1.40,8861.0,1580.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,"On Spr Road, Sector 69 Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Tulip violet is one of the most popular destin...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."

In [29]:
df['sector'] = df['sector'].str.lower()

In [31]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 79 Gurgaon,flat,mapsko mount ville,sector 79,1.30,8024.0,1620.0,Super Built up area 1620(150.5 sq.m.)Carpet ar...,3,3,2,"study room,pooja room","Sector 79 Gurgaon, Gurgaon, Haryana",6.0,West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This beautiful 3 bhk flat in sector 79 gurgaon...,"['6 Wardrobe', '1 Stove', '1 Chimney', '4 AC',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,4 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,sector 112,5.20,10726.0,4848.0,Super Built up area 4848(450.39 sq.m.)Built Up...,4,6,3+,"servant room,pooja room","301, Sector 112 Gurgaon, Gurgaon, Haryana",15.0,East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",This 4 bhk apartment is available for sale in ...,"['6 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sohna,flat,signature global park,sohna,0.95,7846.0,1211.0,Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...,3,2,3+,not available,"Sohna, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Low rise building, all amenities are available...",[],"['Security / Fire Alarm', 'Lift(s)', 'Swimming...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
3,4 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,nirvana country,3.99,8866.0,(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),4,5,3+,servant room,"Nirvana Country, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",This is an newly constructed villa located in ...,"['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,sector 69,1.40,8861.0,1580.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,"On Spr Road, Sector 69 Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Tulip violet is one of the most popular destin...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."

In [33]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 65                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 70                                                     53
nirvana country                                               53
sector 37c                                                    53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
dlf phase 1                                                   43
dlf phase 2                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
laxman vihar                                                  27
sector 54                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
sector 67a                                                    22
dlf phase 3                                                   22
sector 111                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sector 110                                                    16
sushant lok phase 3                                           16
sector 60                                                     15
sector 63                                                     15
sector 14                                                     15
sector 53                                                     14
rajendra park                                                 14
sector 1 imt manesar                                          14
sector 52                                                     14
sector 76                                                     14
dlf phase 5                                                   14
gwal pahari                                                   14
sector 3                                                      14
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 46                                                     13
uppals southend                                               12
sohna road                                                    12
sector 31                                                     12
sector 50                                                     12
sector 39                                                     12
sector 93                                                     12
sector 38                                                     12
sector 9a                                                     11
sector 47                                                     11
ashok vihar phase 3 extension                                 11
sector 1a imt manesar                                         10
sector 7                                                      10
south city 1                                                   9
ashok vihar phase 2                                            9
sector 55                                                      9
sector 95a                                                     9
sector 4                                                       9
dwarka expressway                                              8
palam vihar extension                                          8
sector 89 a                                                    8
c block sushant lok phase 1                                    8
sector 40                                                      8
sector 59                                                      8
mehrauli  road                                                 8
malibu town                                                    8
sector 43                                                      8
sector 10a                                                     8
sector 57                                                      8
sector 36 sohna                                                7
sector 26                                                      7
sector 58                                                      7
sector 51                                                      7
surat nagar 1                                                  7
sector 11                                                      7
new colony                                                     7
mianwali colony                                                7
jyoti park                                                     6
rajiv nagar                                                    6
sector 5                                                       6
jacobpura                                                      6
sector 1                                                       6
ashok vihar                                                    6
saraswati vihar                                                5
dayanand colony                                                5
manesar                                                        5
sector 105                                                     5
sector 23a                                                     5
ansal plaza                                                    5
sector 9                                                       5
chakkarpur                                                     5
sector 28                                                      5
sector 2                                                       5
greenwood city                                                 5
sector 30                                                      5
new palam vihar                                                5
sector 80                                                      5
sushant lok phase 2                                            5
subhash nagar                                                  5
arjun nagar                                                    5
shivaji nagar                                                  4
sector 12a                                                     4
ravi nagar                                                     4
valley view estate                                             4
sector 12                                                      4
garhi harsaru                                                  4
sector 17                                                      4
vishnu garden                                                  4
devilal colony                                                 4
new                                                            4
krishna colony                                                 4
shivpuri                                                       4
suncity                                                        4
sector 36                                                      4
sector 3a                                                      4
imt manesar                                                    4
surya vihar                                                    4
baldev nagar                                                   4
bhondsi                                                        4
adarsh nagar                                                   4
sector 6                                                       4
sector 45                                                      4
bhim nagar                                                     4
dharam colony                                                  4
madanpuri                                                      4
b block sushant lok phase 1                                    3
maruti kunj                                                    3
sector 17a                                                     3
sector 8                                                       3
gandhi nagar                                                   3
sector 110 a                                                   3
sector 73                                                      3
prem nagar                                                     3
sector 27                                                      3
sector 23                                                      3
shakti nagar                                                   3
sector 15                                                      3
sector 17b                                                     3
a block sushant lok phase 1                                    3
laxmi garden                                                   3
patel nagar                                                    3
sector 88b                                                     3
mg road                                                        3
sispal vihar                                                   2
rajiv chowk                                                    2
sector 24                                                      2
nars                                                           2
block a surya vihar                                            2
west rajiv nagar                                               2
sector-2 sohna                                                 2
golf course ext road                                           2
shanti nagar                                                   2
sector-11 sohna                                                2
ambience island                                                2
manohar nagar                                                  2
sushant lok                                                    2
bissar                                                         2
samaspur                                                       2
sector 41                                                      2
pratap nagar                                                   2
sector 15 part 2                                               2
golf course road                                               2
new palam vihar phase 2                                        2
new basti                                                      2
mohan nagar                                                    2
faridabad road                                                 2
rosewood                                                       2
iffco chowk                                                    2
farukhnagar                                                    2
sector 15 part 1                                               2
shankar vihar                                                  2
mayfield garden                                                2
new palam vihar phase 1                                        2
lajpat nagar                                                   2
hira nagar                                                     2
acharya puri                                                   2
bhawani enclave                                                2
sohna  road                                                    2
surat nagar phase 2                                            2
sector 32                                                      2
, delhi ncr                                                    2
daulatabad                                                     2
surat nagar                                                    2
sector 21                                                      2
sheetla colony                                                 2
ram nagar                                                      1
bhimgarh kheri phase 3                                         1
pataudi road                                                   1
sector 21a faridabad                                           1
rajiv colony                                                   1
sultanpur                                                      1
heritage city                                                  1
huda saraswati vihar                                           1
b1 block sector 57                                             1
shivji park colony                                             1
sector-35 sohna                                                1
sector 37a                                                     1
ashok vihar phase i                                            1
rattan garden                                                  1
nirvana country pocket h                                       1
new colony, sector 7                                           1
block g sector-57                                              1
civil l                                                        1
kanahi                                                         1
sector 17c                                                     1
saraswati enclave                                              1
ravi nager basai road                                          1
kheri                                                          1
park view                                                      1
garauli kalan                                                  1
near euro                                                      1
urban estate, sector 5                                         1
sector 13                                                      1
dhankot                                                        1
khandsa                                                        1
part 3 sector 5                                                1
near nand hospital                                             1
jacobpura near sadar bazar                                     1
sai kunj                                                       1
vir nagar                                                      1
laxmna vihar, phase 2                                          1
carterpuri village                                             1
block h ashok vihar phase iii extension                        1
alipur                                                         1
sadar bazar                                                    1
sector 37b                                                     1
ats marigold                                                   1
sec 3 bhim vihar part 1 bhimgher kheri                         1
saroop garden rajendra park                                    1
sector 5 chowk                                                 1
anand garden, sector-105                                       1
near khandsa road                                              1
ansal's palam vihar                                            1
hno 13 sagar enclave sura                                      1
sector-5 sheetla colony                                        1
sector 4 urban estate                                          1
ashok vihar phase 3                                            1
laxman vihar, railway road,                                    1
tekchand nagar                                                 1
g block dlf city phase 1                                       1
hsiidc plot sector 1 imt manesar                               1
sector 42                                                      1
devi lal colony gali no 12 gurgaon nr omkar public school      1
mahavir pura                                                   1
godrej aria , sector 79 ,                                      1
old delhi road, opp sector-14                                  1
sector-7 hous                                                  1
near sector 1 market                                           1
v block dlf phase 3                                            1
bhora kalan                                                    1
sector 9b                                                      1
damdma                                                         1
near pataudi chowk                                             1
bptp                                                           1
jat colony,fazilpur/taj nagar road                             1
om nagar                                                       1
naharpur rupa                                                  1
new jyoti park                                                 1
gopal nagar, garhi ghasita, sonipat                            1
cyber city                                                     1
south city                                                     1
udyog vihar phase 1                                            1
sector-5 sohna                                                 1
mahalaxmi garden, rajendra place                               1
begampur khatola                                               1
lucknow                                                        1
Name: count, dtype: int64

In [35]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [39]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [41]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 90                      90
sector 65                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 43                      53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 82                      42
sector 61                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 24                      24
sector 57                      24
sector 112                     24
sector 105                     23
sector 14                      23
sector 33                      23
sector 88a                     23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 22                      20
sector 3                       20
sector 82a                     20
sector 47                      19
sector 78                      19
sector 74                      18
gwal pahari                    18
sector 63a                     18
sector 62                      17
sector 91                      17
sector 110                     16
sector 99                      16
sector 60                      15
sector 63                      15
sector 53                      14
sector 1 manesar               14
sector 52                      14
sector 76                      14
sector 55                      14
sector 36a                     13
sector 4 phase 2               13
sector 9                       13
sector 46                      13
sector 6                       13
sector 93                      12
sector 38                      12
sohna road road                12
sector 31                      12
sector 39                      12
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 13                      10
sector 1a manesar              10
sector 95a                      9
manesar                         9
sector 3 phase 2                9
sector 45                       9
sector 8                        8
sector 2 extension              8
sector 10a                      8
sector 17                       8
dwarka expressway               8
c block sector 43               8
sector 40                       8
sector 89 a                     8
sector 59                       8
sector 23                       8
sector 36 sohna road            7
sector 58                       7
sector 51                       7
sector 5                        6
sector 21                       6
sector 1                        6
sector 30                       5
sector 23a                      5
new sector 2                    5
sector 80                       5
sector 12a                      4
sector 3a                       4
sector 36                       4
new                             4
sector 88b                      3
sector 73                       3
a block sector 43               3
patel nagar                     3
b block sector 43               3
maruti kunj                     3
sector 27                       3
sector 17b                      3
sector 15                       3
sector 110 a                    3
sector 17a                      3
Name: count, dtype: int64

In [43]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [45]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
458,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
1170,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
2106,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2940,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [47]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [49]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
110,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
859,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,(100 sq.m.) Plot Area,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,servant room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1198,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
1639,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,(25 sq.m.) Plot Area,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2795,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [51]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [53]:
df.shape

(3803, 21)

In [55]:
df.duplicated().sum()

0

In [57]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 79 Gurgaon,flat,mapsko mount ville,sector 79,1.30,8024.0,1620.0,Super Built up area 1620(150.5 sq.m.)Carpet ar...,3,3,2,"study room,pooja room","Sector 79 Gurgaon, Gurgaon, Haryana",6.0,West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This beautiful 3 bhk flat in sector 79 gurgaon...,"['6 Wardrobe', '1 Stove', '1 Chimney', '4 AC',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,4 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,sector 112,5.20,10726.0,4848.0,Super Built up area 4848(450.39 sq.m.)Built Up...,4,6,3+,"servant room,pooja room","301, Sector 112 Gurgaon, Gurgaon, Haryana",15.0,East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",This 4 bhk apartment is available for sale in ...,"['6 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sohna,flat,signature global park,sohna road,0.95,7846.0,1211.0,Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...,3,2,3+,not available,"Sohna, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Low rise building, all amenities are available...",[],"['Security / Fire Alarm', 'Lift(s)', 'Swimming...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
3,4 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,sector 50,3.99,8866.0,(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),4,5,3+,servant room,"Nirvana Country, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",This is an newly constructed villa located in ...,"['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,sector 69,1.40,8861.0,1580.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,"On Spr Road, Sector 69 Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Tulip violet is one of the most popular destin...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."

In [59]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [61]:
df.shape

(3803, 17)

In [63]:
df.head()

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
0,flat,mapsko mount ville,sector 79,1.30,8024.0,1620.0,Super Built up area 1620(150.5 sq.m.)Carpet ar...,3,3,2,"study room,pooja room",6.0,West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...","['6 Wardrobe', '1 Stove', '1 Chimney', '4 AC',...","['Centrally Air Conditioned', 'Water purifier'..."
1,flat,experion windchants,sector 112,5.20,10726.0,4848.0,Super Built up area 4848(450.39 sq.m.)Built Up...,4,6,3+,"servant room,pooja room",15.0,East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","['6 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'..."
2,flat,signature global park,sohna road,0.95,7846.0,1211.0,Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...,3,2,3+,not available,1.0,NaN,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...",[],"['Security / Fire Alarm', 'Lift(s)', 'Swimming..."
3,house,nirvana cedar crest,sector 50,3.99,8866.0,(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),4,5,3+,servant room,4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...","['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,flat,tulip violet,sector 69,1.40,8861.0,1580.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,2.0,North-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."

In [65]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)